#### Investigating whether yield trends in major producing countries can be used to predict yields in other countries

#### Exploratory Data Analysis

Quick explore of additional data

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
importexport = pd.read_csv('../data/import_export_data.csv')
clean_yield = pd.read_csv('../data/extracleaned_wheat_data.csv')

In [21]:
importexport

,Domain,Area,Element,Item,Year,Unit,Value
0,Crops and livestock products,Afghanistan,Import quantity,Wheat,1961,t,32400.00
1,Crops and livestock products,Afghanistan,Import quantity,Wheat,1962,t,6800.00
2,Crops and livestock products,Afghanistan,Import quantity,Wheat,1963,t,79900.00
3,Crops and livestock products,Afghanistan,Import quantity,Wheat,1964,t,106092.00
4,Crops and livestock products,Afghanistan,Import quantity,Wheat,1965,t,107000.00
...,...,...,...,...,...,...,...
18291,Crops and livestock products,Zimbabwe,Import quantity,Wheat,2021,t,180725.49
18292,Crops and livestock products,Zimbabwe,Import quantity,Wheat,2022,t,172774.30
18293,Crops and livestock products,Zimbabwe,Export quantity,Wheat,2022,t,10.50
18294,Crops and livestock products,Zimbabwe,Import quantity,Wheat,2023,t,258404.63
18295,Crops and livestock products,Zimbabwe,Export quantity,Wheat,2023,t,124.30

In [22]:
importexport = importexport.drop(columns=['Domain','Item','Unit'])

In [23]:
importexport

              Area          Element  Year      Value
0      Afghanistan  Import quantity  1961   32400.00
1      Afghanistan  Import quantity  1962    6800.00
2      Afghanistan  Import quantity  1963   79900.00
3      Afghanistan  Import quantity  1964  106092.00
4      Afghanistan  Import quantity  1965  107000.00
...            ...              ...   ...        ...
18291     Zimbabwe  Import quantity  2021  180725.49
18292     Zimbabwe  Import quantity  2022  172774.30
18293     Zimbabwe  Export quantity  2022      10.50
18294     Zimbabwe  Import quantity  2023  258404.63
18295     Zimbabwe  Export quantity  2023     124.30

[18296 rows x 4 columns]

In [24]:
clean_yield

,Area Code,Area,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,Y1968,...,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Y2021,Y2022,Y2023
0,2,Afghanistan,1022.0,973.5,831.7,951.0,972.3,866.6,1123.2,1156.2,...,2023.7,2195.9,1980.3,2034.2,2210.0,2095.1,1943.4,1963.1,2045.3,2146.7
1,3,Albania,773.1,1052.2,712.7,962.5,1134.4,1239.8,1355.0,1412.4,...,4000.1,3951.1,3900.0,4036.7,3692.7,4068.0,4327.1,4130.5,4296.3,4053.9
2,4,Algeria,406.0,804.5,832.6,531.7,605.7,425.2,633.3,689.9,...,1475.3,1464.0,1183.3,1150.1,2043.3,1963.0,1681.1,1584.3,1666.7,1388.9
3,7,Angola,1111.1,1111.1,1111.1,928.6,1111.1,1100.0,1350.0,1350.0,...,977.9,962.2,946.6,931.0,915.3,879.8,652.0,931.0,931.0,931.0
4,9,Argentina,1295.0,1522.2,1575.1,1835.3,1321.2,1198.2,1259.5,983.3,...,2661.9,2810.0,2862.3,3304.7,3180.6,3216.0,2938.7,2759.5,3382.5,2287.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,5801,Least Developed Countries,935.1,907.4,815.0,891.1,901.3,843.9,982.9,998.5,...,2291.8,2520.8,2304.2,2424.5,2524.9,2523.2,2473.3,2577.7,2588.3,2615.3
119,5802,Land Locked Developing Countries,948.9,957.4,836.4,939.7,953.8,852.4,1075.9,1047.9,...,1770.8,1888.8,1874.3,1861.9,1853.8,1851.4,1889.1,1748.6,1922.4,1777.3
120,5803,Small Island Developing States,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,3000.0,2687.5,...,1310.8,702.2,654.3,601.7,522.4,592.8,509.4,561.8,550.3,537.7
121,5815,Low Income Food Deficit Countries,835.3,917.9,802.8,855.0,901.5,818.8,967.6,954.9,...,2525.6,2851.4,2581.9,2579.8,2575.3,2794.7,2725.7,2617.8,2754.1,2921.3
122,5817,Net Food Importing Developing Countries,853.9,952.4,906.5,951.5,953.4,845.1,915.3,1115.8,...,2677.6,2807.0,2644.4,2820.2,2890.9,2765.3,2653.1,3032.3,2811.9,3007.7

In [25]:
importexport_wide = importexport.pivot_table(
    index=["Area", "Element"],
    columns = "Year",
    values = "Value"
)

In [26]:
importexport_wide

Year                              1961      1962       1963      1964  \
Area         Element
Afghanistan  Export quantity       NaN       NaN        NaN       NaN
             Import quantity   32400.0    6800.0    79900.0  106092.0
Albania      Export quantity       0.0       0.0        0.0       0.0
             Import quantity  182400.0   89100.0   109800.0  110700.0
Algeria      Export quantity     270.0     300.0      242.0   15000.0
...                                ...       ...        ...       ...
Yugoslav SFR Import quantity  745504.0  734612.0  1438831.0  610672.0
Zambia       Export quantity       NaN       NaN        NaN       NaN
             Import quantity   21000.0   16000.0    21000.0   18900.0
Zimbabwe     Export quantity       0.0     800.0     1500.0    5700.0
             Import quantity   84880.0   63680.0    82380.0   78800.0

Year                               1965       1966      1967     1968  \
Area         Element
Afghanistan  Export quantity        NaN        NaN       NaN      NaN
             Import quantity   107000.0   118838.0  140082.0  60000.0
Albania      Export quantity        0.0        0.0       0.0      0.0
             Import quantity   135790.0   115121.0   94337.0  86497.0
Algeria      Export quantity    76000.0        0.0       0.0      0.0
...                                 ...        ...       ...      ...
Yugoslav SFR Import quantity  1192609.0  1357807.0  411441.0  81588.0
Zambia       Export quantity        NaN        NaN       NaN      NaN
             Import quantity    25900.0    34783.0   30281.0  58599.0
Zimbabwe     Export quantity     6000.0        0.0       0.0      0.0
             Import quantity    90300.0    92622.0   90000.0  81690.0

Year                             1969      1970  ...       2014       2015  \
Area         Element                             ...
Afghanistan  Export quantity      NaN       NaN  ...       0.00       0.00
             Import quantity  87800.0   30000.0  ...   78730.00  176538.59
Albania      Export quantity      0.0       0.0  ...        NaN        NaN
             Import quantity  72332.0   76640.0  ...  268809.00  235833.19
Algeria      Export quantity      0.0       0.0  ...      27.38      11.00
...                               ...       ...  ...        ...        ...
Yugoslav SFR Import quantity  22626.0   14189.0  ...        NaN        NaN
Zambia       Export quantity      NaN       NaN  ...    8918.76      21.00
             Import quantity  45863.0  106926.0  ...       1.30   41870.41
Zimbabwe     Export quantity      0.0       0.0  ...       1.00    1510.00
             Import quantity  57269.0   57020.0  ...  201009.77  231292.70

Year                               2016       2017       2018       2019  \
Area         Element
Afghanistan  Export quantity       0.01        NaN        NaN        NaN
             Import quantity  258472.69  728124.00  692468.00  457458.88
Albania      Export quantity     741.08        NaN        NaN        NaN
             Import quantity  207007.82  178363.04  194876.35  144425.67
Algeria      Export quantity        NaN      14.33      55.01       2.00
...                                 ...        ...        ...        ...
Yugoslav SFR Import quantity        NaN        NaN        NaN        NaN
Zambia       Export quantity      34.00        NaN        NaN        NaN
             Import quantity    5184.61   54350.28   30069.09   31178.38
Zimbabwe     Export quantity       0.03   16500.05       7.05     300.00
             Import quantity  268891.25  205759.81  276775.63  124632.02

Year                               2020       2021       2022       2023
Area         Element
Afghanistan  Export quantity      20.68        NaN        NaN       0.01
             Import quantity  598254.11  575749.94  733011.93  482890.19
Albania      Export quantity        NaN        NaN        NaN     219.82
             Import quantity  239702.36   41349.44   88452.32  115481.39
Algeria      Export quantity       5.10    2547.57     308.36      24.77
...                                 ...        ...        ...        ...
Yugoslav SFR Import quantity        NaN        NaN        NaN        NaN
Zambia       Export quantity     242.53     944.40      30.00     995.00
             Import quantity   51684.46   60566.14   38068.94   60381.91
Zimbabwe     Export quantity    2083.00        NaN      10.50     124.30
             Import quantity  244249.01  180725.49  172774.30  258404.63

[384 rows x 63 columns]

In [27]:
clean_yield = clean_yield[clean_yield["Area Code"] < 5000]
clean_yield.drop(columns=["Area Code"], inplace=True)
countries = clean_yield["Area"].unique().tolist()
#importexport_wide_filtered = importexport_wide[importexport_wide[index].isin(countries)]
countries

/var/folders/6z/5ds6pqr14hq4rzt701_p13lr0000gn/T/ipykernel_67107/478073910.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_yield.drop(columns=["Area Code"], inplace=True)

['Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Argentina',
 'Australia',
 'Austria',
 'Bangladesh',
 'Bhutan',
 'Bolivia (Plurinational State of)',
 'Botswana',
 'Brazil',
 'Bulgaria',
 'Burundi',
 'Canada',
 'Chad',
 'Chile',
 'China',
 'China, mainland',
 'China, Taiwan Province of',
 'Colombia',
 'Cyprus',
 'Democratic Peoples Republic of Korea',
 'Democratic Republic of the Congo',
 'Denmark',
 'Ecuador',
 'Egypt',
 'Eswatini',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Guatemala',
 'Honduras',
 'Hungary',
 'India',
 'Iran (Islamic Republic of)',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Japan',
 'Jordan',
 'Kenya',
 'Lebanon',
 'Lesotho',
 'Libya',
 'Malawi',
 'Mali',
 'Malta',
 'Mauritania',
 'Mexico',
 'Mongolia',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands (Kingdom of the)',
 'New Caledonia',
 'New Zealand',
 'Niger',
 'Nigeria',
 'Norway',
 'Oman',
 'Pakistan',
 'Paraguay',
 'Peru',
 'Poland',
 'Portugal',
 'Qatar',
 'Republic of Korea',
 'Romania',
 'Rwanda',
 'Saudi Arabia',
 'Somalia',
 'South Africa',
 'Spain',
 'Sudan (former)',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Tunisia',
 'Türkiye',
 'Uganda',
 'United Kingdom of Great Britain and Northern Ireland',
 'United Republic of Tanzania',
 'United States of America',
 'Uruguay',
 'Venezuela (Bolivarian Republic of)',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [29]:
importexport_wide_filtered = importexport_wide[importexport_wide["Area"].isin(countries)]

KeyError: 'Area'